### ISSUE TITLE
ACTION_PAUSE_RAISE_Z	 Raises Z too high and very slow

### ISSUE THREAD

**Issue by Ksdmg** [nunorvoliveira/snapmaker-2.0#1]
**Describe the bug**
The command ACTION_PAUSE_RAISE_Z	 raises Z to 9999 ->
```
// Raises Z axix to Z9999
                writeBlock(gMotionModal.format(1), zOutput.format(9999), feedOutput.format(200));
```
Could we reduce this to the max Z height that Snapmaker is capable of? Luban would benefit from it, as this currently breaks the preview and the time calculation on the machine itself.

In addition, could we increase the speed before the Z raise? I think at the moment it uses the last feedrate set.

However, thank you very much for sharing this! This already helped me alot!

**Comment by nunorvoliveira** [comment]
Hello @Ksdmg. Thank you for pointing this out!

I've changed the post processor to move the machine to Z=334mm in machine coordinates (The maximum for A350).
In addition, I've implemented 2 variables to control the speed going up and down on the pause command.
By default the machine now goes up at 3000mm/min and after the pause it goes down at 1500mm/min.

Cheers!
