### ISSUE TITLE
Support for new CNC Module

### ISSUE THREAD

**Issue by tylerhartwig** [nunorvoliveira/snapmaker-2.0#6]
I'm wondering what, if anything needs to be done to support the new CNC module that Snapmaker has released for 2.0. I'm assuming at this point all that needs to be done is adjust the spindle speeds?

If not, would be happy to contribute! but wanted to check in ahead of receiving my new module.

**Comment by nunorvoliveira** [comment]
Hi,

I would assume that the spindle speed would be the only thing but I didn't kept  using the snapmaker and I'm not even aware of the new module specs.
In theory all is the same as it's the same machine and the speeds seem to be the only module specific parameter.

**Comment by tylerhartwig** [comment]
Awesome appreciate that! Haven't tried the post-processor yet but planning to today, appreciate that you put it together
